development:
  adapter: mysql2
  database: foundation_development
  host: localhost
  user: root
  password:
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: foundation_test
  host: localhost
  user: root
  password:
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: foundation_production
  host: localhost
  user: root
  password:
  pool: 5
  timeout: 5000
